### ISSUE TITLE
Get TODO location by its ID

### ISSUE THREAD

**Issue by rexim** [rexim/todo#5]
In a form of `<file-path>:<line-number>: <todo-title>`

---

### Pieces
- [x] #7 Initial implementation of getting TODO by its ID
- [x] ~#8 Traversable layer of abstraction over FS APIs from Sys module~
- [x] #11 Implement file_stream_of_dir_tree and root_of_git_repo
